"""add_prds_table

Revision ID: 16a2e296ae74
Revises: f0b729246e42
Create Date: 2025-08-03 16:57:07.848547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a2e296ae74'
down_revision = 'f0b729246e42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 