"""make_retriever_type_non_nullable

Revision ID: 316458f62f0b
Revises: ee4271fed7fc
Create Date: 2025-08-04 15:58:08.605767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316458f62f0b'
down_revision = 'ee4271fed7fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 