"""Add import flags to notion settings

Revision ID: f0b729246e42
Revises: f7782f3ad185
Create Date: 2025-08-02 18:44:57.617482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0b729246e42'
down_revision = 'f7782f3ad185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.alter_column('notion_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notion_chunks_page_id'), table_name='notion_chunks')
    op.alter_column('notion_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notion_comments_page_id'), table_name='notion_comments')
    op.drop_constraint(op.f('notion_comments_notion_comment_id_key'), 'notion_comments', type_='unique')
    op.drop_index(op.f('ix_notion_comments_notion_comment_id'), table_name='notion_comments')
    op.create_index(op.f('ix_notion_comments_notion_comment_id'), 'notion_comments', ['notion_comment_id'], unique=True)
    op.alter_column('notion_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notion_pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notion_pages_page_type'), table_name='notion_pages')
    op.drop_index(op.f('ix_notion_pages_user_id'), table_name='notion_pages')
    op.drop_constraint(op.f('notion_pages_notion_page_id_key'), 'notion_pages', type_='unique')
    op.drop_index(op.f('ix_notion_pages_notion_page_id'), table_name='notion_pages')
    op.create_index(op.f('ix_notion_pages_notion_page_id'), 'notion_pages', ['notion_page_id'], unique=True)
    op.add_column('notion_settings', sa.Column('import_prd', sa.Boolean(), nullable=True))
    op.add_column('notion_settings', sa.Column('import_research', sa.Boolean(), nullable=True))
    op.add_column('notion_settings', sa.Column('import_analytics', sa.Boolean(), nullable=True))
    op.alter_column('notion_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notion_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notion_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notion_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('notion_settings', 'import_analytics')
    op.drop_column('notion_settings', 'import_research')
    op.drop_column('notion_settings', 'import_prd')
    op.drop_index(op.f('ix_notion_pages_notion_page_id'), table_name='notion_pages')
    op.create_index(op.f('ix_notion_pages_notion_page_id'), 'notion_pages', ['notion_page_id'], unique=False)
    op.create_unique_constraint(op.f('notion_pages_notion_page_id_key'), 'notion_pages', ['notion_page_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notion_pages_user_id'), 'notion_pages', ['user_id'], unique=False)
    op.create_index(op.f('ix_notion_pages_page_type'), 'notion_pages', ['page_type'], unique=False)
    op.alter_column('notion_pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notion_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notion_comments_notion_comment_id'), table_name='notion_comments')
    op.create_index(op.f('ix_notion_comments_notion_comment_id'), 'notion_comments', ['notion_comment_id'], unique=False)
    op.create_unique_constraint(op.f('notion_comments_notion_comment_id_key'), 'notion_comments', ['notion_comment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notion_comments_page_id'), 'notion_comments', ['page_id'], unique=False)
    op.alter_column('notion_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notion_chunks_page_id'), 'notion_chunks', ['page_id'], unique=False)
    op.alter_column('notion_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    op.alter_column('chats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ### 